// ── Theme system ─────────────────────────────────────────────────────────────
//
// All widget colors are driven by CSS custom properties (--wt-*).
// Themes define the full set of vars. The active theme + any custom overrides
// are applied to :root by the theme store applier.
//
// Each theme also carries a `background` that is applied to the whiteboard
// canvas whenever the user picks that theme.

import { type Background } from '../constants/backgrounds'

export interface ThemeVars {
  // Widget frame
  widgetBg:           string
  widgetBorder:       string
  widgetBorderActive: string
  shadowSm:           string
  shadowMd:           string
  shadowLg:           string
  backdropFilter:     string

  // Text
  textPrimary: string
  textMuted:   string

  // Surfaces
  surfaceSubtle: string
  surfaceHover:  string
  surfaceDanger: string

  // Accent + danger
  accent:      string
  accentText:  string
  danger:      string

  // Action panel (floating controls)
  actionBg:     string
  actionBorder: string

  // Settings panel
  settingsBg:      string
  settingsBorder:  string
  settingsDivider: string
  settingsLabel:   string
  scrollThumb:     string

  // Clock widget
  clockFaceFill:   string
  clockFaceStroke: string
  clockTickMajor:  string
  clockTickMinor:  string
  clockHands:      string
  clockSecond:     string
  clockCenter:     string

  // Note widget
  noteDefaultBg: string

  // Status colors
  success: string
  info:    string
}

export interface Theme {
  id:            string
  name:          string
  emoji:         string
  dark:          boolean
  previewColors: [string, string, string, string]  // bg, border, accent, text
  background:    Background
  vars:          ThemeVars
}

// ── CSS var map ───────────────────────────────────────────────────────────────

export const VAR_LABELS: Partial<Record<keyof ThemeVars, string>> = {
  widgetBg:           'Widget Background',
  widgetBorder:       'Border',
  widgetBorderActive: 'Border (Active)',
  textPrimary:        'Text',
  textMuted:          'Text Muted',
  surfaceHover:       'Hover Surface',
  accent:             'Accent Color',
  danger:             'Danger Color',
  actionBg:           'Action Panel BG',
  clockFaceFill:      'Clock Face',
  clockHands:         'Clock Hands',
  clockSecond:        'Clock Second Hand',
  noteDefaultBg:      'Note Default BG',
}

// ── Preset themes ─────────────────────────────────────────────────────────────
// Light themes first, then dark themes

export const THEMES: Theme[] = [
  // ── Light ─────────────────────────────────────────────────────────────────
  {
    id: 'minimal',
    name: 'Minimal',
    emoji: '○',
    dark: false,
    previewColors: ['#ffffff', '#e7e5e4', '#3b82f6', '#1c1917'],
    background: { label: 'White', bg: '#ffffff', dot: '#e2e8f0' },
    vars: {
      widgetBg:           '#ffffff',
      widgetBorder:       '#e7e5e4',
      widgetBorderActive: '#d6d3d1',
      shadowSm:           '0 1px 3px rgba(0,0,0,0.08), 0 1px 2px rgba(0,0,0,0.05)',
      shadowMd:           '0 4px 12px rgba(0,0,0,0.1), 0 2px 4px rgba(0,0,0,0.06)',
      shadowLg:           '0 20px 40px rgba(0,0,0,0.15), 0 8px 16px rgba(0,0,0,0.08)',
      backdropFilter:     'none',
      textPrimary:        '#1c1917',
      textMuted:          '#a8a29e',
      surfaceSubtle:      '#f5f5f4',
      surfaceHover:       '#e8e5e3',
      surfaceDanger:      '#fef2f2',
      accent:             '#3b82f6',
      accentText:         '#ffffff',
      danger:             '#f87171',
      actionBg:           '#ffffff',
      actionBorder:       '#e7e5e4',
      settingsBg:         '#ffffff',
      settingsBorder:     '#e7e5e4',
      settingsDivider:    '#f5f5f4',
      settingsLabel:      '#a8a29e',
      scrollThumb:        '#d6d3d1',
      clockFaceFill:      '#ffffff',
      clockFaceStroke:    '#e7e5e4',
      clockTickMajor:     '#a8a29e',
      clockTickMinor:     '#d6d3d1',
      clockHands:         '#1c1917',
      clockSecond:        '#ef4444',
      clockCenter:        '#1c1917',
      noteDefaultBg:      '#fef9c3',
      success:            '#22c55e',
      info:               '#3b82f6',
    },
  },
  {
    id: 'slate',
    name: 'Slate',
    emoji: '▣',
    dark: false,
    previewColors: ['#f8fafc', '#cbd5e1', '#3b82f6', '#0f172a'],
    background: { label: 'Slate', bg: '#f1f5f9', dot: '#cbd5e1' },
    vars: {
      widgetBg:           '#f8fafc',
      widgetBorder:       '#cbd5e1',
      widgetBorderActive: '#94a3b8',
      shadowSm:           '0 1px 3px rgba(15,23,42,0.07)',
      shadowMd:           '0 4px 12px rgba(15,23,42,0.1)',
      shadowLg:           '0 20px 40px rgba(15,23,42,0.14)',
      backdropFilter:     'none',
      textPrimary:        '#0f172a',
      textMuted:          '#94a3b8',
      surfaceSubtle:      '#f1f5f9',
      surfaceHover:       '#e2e8f0',
      surfaceDanger:      '#fef2f2',
      accent:             '#3b82f6',
      accentText:         '#ffffff',
      danger:             '#ef4444',
      actionBg:           '#f8fafc',
      actionBorder:       '#cbd5e1',
      settingsBg:         '#f8fafc',
      settingsBorder:     '#cbd5e1',
      settingsDivider:    '#e2e8f0',
      settingsLabel:      '#94a3b8',
      scrollThumb:        '#cbd5e1',
      clockFaceFill:      '#f8fafc',
      clockFaceStroke:    '#cbd5e1',
      clockTickMajor:     '#94a3b8',
      clockTickMinor:     '#cbd5e1',
      clockHands:         '#0f172a',
      clockSecond:        '#3b82f6',
      clockCenter:        '#0f172a',
      noteDefaultBg:      '#f1f5f9',
      success:            '#22c55e',
      info:               '#3b82f6',
    },
  },
  {
    id: 'paper',
    name: 'Paper',
    emoji: '▪',
    dark: false,
    previewColors: ['#faf8f5', '#e0d8cc', '#5c4a32', '#2d2016'],
    background: { label: 'Parchment', bg: '#f5f0eb', dot: '#c9bfb5' },
    vars: {
      widgetBg:           '#faf8f5',
      widgetBorder:       '#e0d8cc',
      widgetBorderActive: '#c9bfb5',
      shadowSm:           '0 1px 3px rgba(80,60,30,0.08)',
      shadowMd:           '0 4px 12px rgba(80,60,30,0.1)',
      shadowLg:           '0 20px 40px rgba(80,60,30,0.14)',
      backdropFilter:     'none',
      textPrimary:        '#2d2016',
      textMuted:          '#a0897a',
      surfaceSubtle:      '#f5f0eb',
      surfaceHover:       '#ede5d8',
      surfaceDanger:      '#fef2f2',
      accent:             '#5c4a32',
      accentText:         '#faf8f5',
      danger:             '#c0392b',
      actionBg:           '#faf8f5',
      actionBorder:       '#e0d8cc',
      settingsBg:         '#faf8f5',
      settingsBorder:     '#e0d8cc',
      settingsDivider:    '#ede5d8',
      settingsLabel:      '#a0897a',
      scrollThumb:        '#c9bfb5',
      clockFaceFill:      '#faf8f5',
      clockFaceStroke:    '#e0d8cc',
      clockTickMajor:     '#a0897a',
      clockTickMinor:     '#c9bfb5',
      clockHands:         '#2d2016',
      clockSecond:        '#8b4513',
      clockCenter:        '#2d2016',
      noteDefaultBg:      '#fef9e7',
      success:            '#4a7c3f',
      info:               '#5c6a8a',
    },
  },
  {
    id: 'amber',
    name: 'Amber',
    emoji: '◇',
    dark: false,
    previewColors: ['#fffbeb', '#fde68a', '#d97706', '#451a03'],
    background: { label: 'Sand', bg: '#fdf6e3', dot: '#d4c5a9' },
    vars: {
      widgetBg:           '#fffbeb',
      widgetBorder:       '#fde68a',
      widgetBorderActive: '#fbbf24',
      shadowSm:           '0 1px 3px rgba(180,120,0,0.08)',
      shadowMd:           '0 4px 12px rgba(180,120,0,0.12)',
      shadowLg:           '0 20px 40px rgba(180,120,0,0.16)',
      backdropFilter:     'none',
      textPrimary:        '#451a03',
      textMuted:          '#d97706',
      surfaceSubtle:      '#fef3c7',
      surfaceHover:       '#fde68a',
      surfaceDanger:      '#fef2f2',
      accent:             '#d97706',
      accentText:         '#ffffff',
      danger:             '#ef4444',
      actionBg:           '#fffbeb',
      actionBorder:       '#fde68a',
      settingsBg:         '#fffbeb',
      settingsBorder:     '#fde68a',
      settingsDivider:    '#fef3c7',
      settingsLabel:      '#b45309',
      scrollThumb:        '#fbbf24',
      clockFaceFill:      '#fffbeb',
      clockFaceStroke:    '#fde68a',
      clockTickMajor:     '#d97706',
      clockTickMinor:     '#fde68a',
      clockHands:         '#451a03',
      clockSecond:        '#d97706',
      clockCenter:        '#451a03',
      noteDefaultBg:      '#fef3c7',
      success:            '#15803d',
      info:               '#b45309',
    },
  },
  {
    id: 'rose',
    name: 'Rose',
    emoji: '◈',
    dark: false,
    previewColors: ['#fff5f7', '#fecdd3', '#e11d48', '#4c0519'],
    background: { label: 'Blush', bg: '#fff0f3', dot: '#fecdd3' },
    vars: {
      widgetBg:           '#fff5f7',
      widgetBorder:       '#fecdd3',
      widgetBorderActive: '#fda4af',
      shadowSm:           '0 1px 3px rgba(225,29,72,0.07)',
      shadowMd:           '0 4px 12px rgba(225,29,72,0.09)',
      shadowLg:           '0 20px 40px rgba(225,29,72,0.13)',
      backdropFilter:     'none',
      textPrimary:        '#4c0519',
      textMuted:          '#fb7185',
      surfaceSubtle:      '#fff1f2',
      surfaceHover:       '#ffe4e6',
      surfaceDanger:      '#ffe4e6',
      accent:             '#e11d48',
      accentText:         '#ffffff',
      danger:             '#e11d48',
      actionBg:           '#fff5f7',
      actionBorder:       '#fecdd3',
      settingsBg:         '#fff5f7',
      settingsBorder:     '#fecdd3',
      settingsDivider:    '#ffe4e6',
      settingsLabel:      '#fda4af',
      scrollThumb:        '#fda4af',
      clockFaceFill:      '#fff5f7',
      clockFaceStroke:    '#fecdd3',
      clockTickMajor:     '#fda4af',
      clockTickMinor:     '#fecdd3',
      clockHands:         '#4c0519',
      clockSecond:        '#e11d48',
      clockCenter:        '#4c0519',
      noteDefaultBg:      '#fff1f2',
      success:            '#15803d',
      info:               '#be123c',
    },
  },
  {
    id: 'sage',
    name: 'Sage',
    emoji: '◆',
    dark: false,
    previewColors: ['#f4f7f4', '#c6d6c6', '#4a7c59', '#1a2e1a'],
    background: { label: 'Meadow', bg: '#edf2ed', dot: '#c6d6c6' },
    vars: {
      widgetBg:           '#f4f7f4',
      widgetBorder:       '#c6d6c6',
      widgetBorderActive: '#8fad8f',
      shadowSm:           '0 1px 3px rgba(30,60,30,0.07)',
      shadowMd:           '0 4px 12px rgba(30,60,30,0.1)',
      shadowLg:           '0 20px 40px rgba(30,60,30,0.14)',
      backdropFilter:     'none',
      textPrimary:        '#1a2e1a',
      textMuted:          '#8fad8f',
      surfaceSubtle:      '#edf2ed',
      surfaceHover:       '#ddeadd',
      surfaceDanger:      '#fef2f2',
      accent:             '#4a7c59',
      accentText:         '#ffffff',
      danger:             '#ef4444',
      actionBg:           '#f4f7f4',
      actionBorder:       '#c6d6c6',
      settingsBg:         '#f4f7f4',
      settingsBorder:     '#c6d6c6',
      settingsDivider:    '#ddeadd',
      settingsLabel:      '#8fad8f',
      scrollThumb:        '#c6d6c6',
      clockFaceFill:      '#f4f7f4',
      clockFaceStroke:    '#c6d6c6',
      clockTickMajor:     '#8fad8f',
      clockTickMinor:     '#c6d6c6',
      clockHands:         '#1a2e1a',
      clockSecond:        '#4a7c59',
      clockCenter:        '#1a2e1a',
      noteDefaultBg:      '#ddeadd',
      success:            '#4a7c59',
      info:               '#2d5a6a',
    },
  },
  // ── Dark ──────────────────────────────────────────────────────────────────
  {
    id: 'midnight',
    name: 'Midnight',
    emoji: '◉',
    dark: true,
    previewColors: ['#141414', '#2a2a2a', '#a3a3a3', '#f5f5f5'],
    background: { label: 'Charcoal', bg: '#1a1a1a', dot: '#2d2d2d' },
    vars: {
      widgetBg:           '#141414',
      widgetBorder:       '#2a2a2a',
      widgetBorderActive: '#3d3d3d',
      shadowSm:           '0 1px 3px rgba(0,0,0,0.5)',
      shadowMd:           '0 4px 16px rgba(0,0,0,0.6)',
      shadowLg:           '0 20px 48px rgba(0,0,0,0.8)',
      backdropFilter:     'none',
      textPrimary:        '#f5f5f5',
      textMuted:          '#737373',
      surfaceSubtle:      '#1a1a1a',
      surfaceHover:       '#262626',
      surfaceDanger:      '#2a1515',
      accent:             '#a3a3a3',
      accentText:         '#000000',
      danger:             '#f87171',
      actionBg:           '#1a1a1a',
      actionBorder:       '#2a2a2a',
      settingsBg:         '#1a1a1a',
      settingsBorder:     '#2a2a2a',
      settingsDivider:    '#222222',
      settingsLabel:      '#525252',
      scrollThumb:        '#404040',
      clockFaceFill:      '#1a1a1a',
      clockFaceStroke:    '#2a2a2a',
      clockTickMajor:     '#525252',
      clockTickMinor:     '#333333',
      clockHands:         '#e5e5e5',
      clockSecond:        '#f87171',
      clockCenter:        '#e5e5e5',
      noteDefaultBg:      '#262626',
      success:            '#4ade80',
      info:               '#60a5fa',
    },
  },
  {
    id: 'stark',
    name: 'Stark',
    emoji: '⬡',
    dark: true,
    previewColors: ['#070c14', '#1a4a70', '#00b4ff', '#c8e8ff'],
    background: { label: 'Abyss', bg: '#070c14', dot: '#0d2035' },
    vars: {
      widgetBg:           '#070c14',
      widgetBorder:       '#0d2035',
      widgetBorderActive: '#1a4a70',
      shadowSm:           '0 1px 4px rgba(0,180,255,0.1)',
      shadowMd:           '0 4px 16px rgba(0,180,255,0.15)',
      shadowLg:           '0 20px 48px rgba(0,180,255,0.2), 0 0 0 1px rgba(0,180,255,0.05)',
      backdropFilter:     'none',
      textPrimary:        '#c8e8ff',
      textMuted:          '#4a7a9b',
      surfaceSubtle:      '#0a1520',
      surfaceHover:       '#0d2035',
      surfaceDanger:      '#1f0a0a',
      accent:             '#00b4ff',
      accentText:         '#000a14',
      danger:             '#ff4444',
      actionBg:           '#0a1520',
      actionBorder:       '#1a4a70',
      settingsBg:         '#0a1520',
      settingsBorder:     '#1a4a70',
      settingsDivider:    '#0d2035',
      settingsLabel:      '#4a7a9b',
      scrollThumb:        '#1a4a70',
      clockFaceFill:      '#070c14',
      clockFaceStroke:    '#1a4a70',
      clockTickMajor:     '#1a6080',
      clockTickMinor:     '#0d2a40',
      clockHands:         '#00b4ff',
      clockSecond:        '#ff4444',
      clockCenter:        '#00b4ff',
      noteDefaultBg:      '#0a1520',
      success:            '#00d084',
      info:               '#00b4ff',
    },
  },
  {
    id: 'forest',
    name: 'Forest',
    emoji: '◆',
    dark: true,
    previewColors: ['#0f1a0f', '#1a3a1a', '#22c55e', '#d4f5d4'],
    background: { label: 'Deep Forest', bg: '#0a150a', dot: '#162616' },
    vars: {
      widgetBg:           '#0f1a0f',
      widgetBorder:       '#1a3a1a',
      widgetBorderActive: '#2a5a2a',
      shadowSm:           '0 1px 3px rgba(0,0,0,0.5)',
      shadowMd:           '0 4px 16px rgba(0,80,0,0.2)',
      shadowLg:           '0 20px 48px rgba(0,80,0,0.3)',
      backdropFilter:     'none',
      textPrimary:        '#d4f5d4',
      textMuted:          '#4a7a4a',
      surfaceSubtle:      '#0d180d',
      surfaceHover:       '#162616',
      surfaceDanger:      '#1a0f0f',
      accent:             '#22c55e',
      accentText:         '#0a150a',
      danger:             '#f87171',
      actionBg:           '#0d180d',
      actionBorder:       '#1a3a1a',
      settingsBg:         '#0d180d',
      settingsBorder:     '#1a3a1a',
      settingsDivider:    '#141f14',
      settingsLabel:      '#3a6a3a',
      scrollThumb:        '#2a5a2a',
      clockFaceFill:      '#0f1a0f',
      clockFaceStroke:    '#1a3a1a',
      clockTickMajor:     '#2a5a2a',
      clockTickMinor:     '#1a3a1a',
      clockHands:         '#a3e8a3',
      clockSecond:        '#22c55e',
      clockCenter:        '#a3e8a3',
      noteDefaultBg:      '#0d180d',
      success:            '#22c55e',
      info:               '#4ade80',
    },
  },
  {
    id: 'ocean',
    name: 'Ocean',
    emoji: '◍',
    dark: true,
    previewColors: ['#021020', '#05294a', '#38bdf8', '#bae6fd'],
    background: { label: 'Midnight', bg: '#0f172a', dot: '#1e293b' },
    vars: {
      widgetBg:           '#021020',
      widgetBorder:       '#05294a',
      widgetBorderActive: '#0c4a6e',
      shadowSm:           '0 1px 4px rgba(0,150,220,0.12)',
      shadowMd:           '0 4px 16px rgba(0,150,220,0.18)',
      shadowLg:           '0 20px 48px rgba(0,150,220,0.25), 0 0 0 1px rgba(56,189,248,0.06)',
      backdropFilter:     'none',
      textPrimary:        '#bae6fd',
      textMuted:          '#1d6b96',
      surfaceSubtle:      '#031828',
      surfaceHover:       '#04223a',
      surfaceDanger:      '#1f0a0a',
      accent:             '#38bdf8',
      accentText:         '#001220',
      danger:             '#f87171',
      actionBg:           '#031828',
      actionBorder:       '#05294a',
      settingsBg:         '#031828',
      settingsBorder:     '#05294a',
      settingsDivider:    '#041c32',
      settingsLabel:      '#1d6b96',
      scrollThumb:        '#0c4a6e',
      clockFaceFill:      '#021020',
      clockFaceStroke:    '#05294a',
      clockTickMajor:     '#0c4a6e',
      clockTickMinor:     '#042038',
      clockHands:         '#7dd3fc',
      clockSecond:        '#38bdf8',
      clockCenter:        '#7dd3fc',
      noteDefaultBg:      '#031828',
      success:            '#34d399',
      info:               '#38bdf8',
    },
  },
  {
    id: 'terminal',
    name: 'Terminal',
    emoji: '▶',
    dark: true,
    previewColors: ['#0a0a0a', '#1a1a1a', '#00ff41', '#00cc33'],
    background: { label: 'Void', bg: '#0a0a0a', dot: '#1a1a1a' },
    vars: {
      widgetBg:           '#0a0a0a',
      widgetBorder:       '#1a1a1a',
      widgetBorderActive: '#00ff41',
      shadowSm:           '0 1px 4px rgba(0,255,65,0.1)',
      shadowMd:           '0 4px 16px rgba(0,255,65,0.12)',
      shadowLg:           '0 20px 48px rgba(0,255,65,0.18)',
      backdropFilter:     'none',
      textPrimary:        '#00ff41',
      textMuted:          '#006618',
      surfaceSubtle:      '#0d0d0d',
      surfaceHover:       '#141414',
      surfaceDanger:      '#1a0000',
      accent:             '#00ff41',
      accentText:         '#000000',
      danger:             '#ff0000',
      actionBg:           '#0d0d0d',
      actionBorder:       '#1a1a1a',
      settingsBg:         '#0d0d0d',
      settingsBorder:     '#1a1a1a',
      settingsDivider:    '#111111',
      settingsLabel:      '#006618',
      scrollThumb:        '#00a828',
      clockFaceFill:      '#0a0a0a',
      clockFaceStroke:    '#00a828',
      clockTickMajor:     '#00a828',
      clockTickMinor:     '#004010',
      clockHands:         '#00ff41',
      clockSecond:        '#00cc33',
      clockCenter:        '#00ff41',
      noteDefaultBg:      '#001408',
      success:            '#00ff41',
      info:               '#00cc33',
    },
  },
  {
    id: 'carbon',
    name: 'Carbon',
    emoji: '◼',
    dark: true,
    previewColors: ['#161b22', '#30363d', '#58a6ff', '#e6edf3'],
    background: { label: 'Ink', bg: '#0d1117', dot: '#21262d' },
    vars: {
      widgetBg:           '#161b22',
      widgetBorder:       '#30363d',
      widgetBorderActive: '#484f58',
      shadowSm:           '0 1px 3px rgba(0,0,0,0.5)',
      shadowMd:           '0 4px 16px rgba(0,0,0,0.6)',
      shadowLg:           '0 20px 48px rgba(0,0,0,0.8)',
      backdropFilter:     'none',
      textPrimary:        '#e6edf3',
      textMuted:          '#484f58',
      surfaceSubtle:      '#0d1117',
      surfaceHover:       '#21262d',
      surfaceDanger:      '#2a1515',
      accent:             '#58a6ff',
      accentText:         '#0d1117',
      danger:             '#f85149',
      actionBg:           '#161b22',
      actionBorder:       '#30363d',
      settingsBg:         '#161b22',
      settingsBorder:     '#30363d',
      settingsDivider:    '#21262d',
      settingsLabel:      '#484f58',
      scrollThumb:        '#30363d',
      clockFaceFill:      '#161b22',
      clockFaceStroke:    '#30363d',
      clockTickMajor:     '#484f58',
      clockTickMinor:     '#30363d',
      clockHands:         '#c9d1d9',
      clockSecond:        '#58a6ff',
      clockCenter:        '#c9d1d9',
      noteDefaultBg:      '#21262d',
      success:            '#3fb950',
      info:               '#58a6ff',
    },
  },
  {
    id: 'dusk',
    name: 'Dusk',
    emoji: '◉',
    dark: true,
    previewColors: ['#12101e', '#2d2850', '#a78bfa', '#ede9fe'],
    background: { label: 'Twilight', bg: '#0e0c1a', dot: '#1e1a35' },
    vars: {
      widgetBg:           '#12101e',
      widgetBorder:       '#2d2850',
      widgetBorderActive: '#4c3d8a',
      shadowSm:           '0 1px 3px rgba(0,0,0,0.5)',
      shadowMd:           '0 4px 16px rgba(80,40,180,0.2)',
      shadowLg:           '0 20px 48px rgba(80,40,180,0.3)',
      backdropFilter:     'none',
      textPrimary:        '#ede9fe',
      textMuted:          '#4c3d8a',
      surfaceSubtle:      '#0e0c1a',
      surfaceHover:       '#1e1a35',
      surfaceDanger:      '#2a1520',
      accent:             '#a78bfa',
      accentText:         '#0e0c1a',
      danger:             '#f87171',
      actionBg:           '#12101e',
      actionBorder:       '#2d2850',
      settingsBg:         '#12101e',
      settingsBorder:     '#2d2850',
      settingsDivider:    '#1e1a35',
      settingsLabel:      '#4c3d8a',
      scrollThumb:        '#4c3d8a',
      clockFaceFill:      '#12101e',
      clockFaceStroke:    '#2d2850',
      clockTickMajor:     '#4c3d8a',
      clockTickMinor:     '#2d2850',
      clockHands:         '#c4b5fd',
      clockSecond:        '#a78bfa',
      clockCenter:        '#c4b5fd',
      noteDefaultBg:      '#1e1a35',
      success:            '#a78bfa',
      info:               '#818cf8',
    },
  },
  {
    id: 'espresso',
    name: 'Espresso',
    emoji: '▪',
    dark: true,
    previewColors: ['#1c1410', '#3d2b1e', '#d97706', '#f5e6d0'],
    background: { label: 'Roast', bg: '#140f0a', dot: '#2a1e12' },
    vars: {
      widgetBg:           '#1c1410',
      widgetBorder:       '#3d2b1e',
      widgetBorderActive: '#6b4226',
      shadowSm:           '0 1px 3px rgba(0,0,0,0.5)',
      shadowMd:           '0 4px 16px rgba(80,40,0,0.3)',
      shadowLg:           '0 20px 48px rgba(80,40,0,0.4)',
      backdropFilter:     'none',
      textPrimary:        '#f5e6d0',
      textMuted:          '#6b4226',
      surfaceSubtle:      '#140f0a',
      surfaceHover:       '#2a1e12',
      surfaceDanger:      '#2a1010',
      accent:             '#d97706',
      accentText:         '#140f0a',
      danger:             '#f87171',
      actionBg:           '#1c1410',
      actionBorder:       '#3d2b1e',
      settingsBg:         '#1c1410',
      settingsBorder:     '#3d2b1e',
      settingsDivider:    '#2a1e12',
      settingsLabel:      '#6b4226',
      scrollThumb:        '#6b4226',
      clockFaceFill:      '#1c1410',
      clockFaceStroke:    '#3d2b1e',
      clockTickMajor:     '#6b4226',
      clockTickMinor:     '#3d2b1e',
      clockHands:         '#e5c9a0',
      clockSecond:        '#d97706',
      clockCenter:        '#e5c9a0',
      noteDefaultBg:      '#2a1e12',
      success:            '#a3724a',
      info:               '#d97706',
    },
  },
  {
    id: 'slate-dark',
    name: 'Slate Dark',
    emoji: '▣',
    dark: true,
    previewColors: ['#0f172a', '#1e293b', '#38bdf8', '#e2e8f0'],
    background: { label: 'Slate Night', bg: '#080f1e', dot: '#162032' },
    vars: {
      widgetBg:           '#0f172a',
      widgetBorder:       '#1e293b',
      widgetBorderActive: '#334155',
      shadowSm:           '0 1px 3px rgba(0,0,0,0.5)',
      shadowMd:           '0 4px 16px rgba(0,0,0,0.6)',
      shadowLg:           '0 20px 48px rgba(0,0,0,0.8)',
      backdropFilter:     'none',
      textPrimary:        '#e2e8f0',
      textMuted:          '#475569',
      surfaceSubtle:      '#080f1e',
      surfaceHover:       '#162032',
      surfaceDanger:      '#2a1515',
      accent:             '#38bdf8',
      accentText:         '#0f172a',
      danger:             '#f87171',
      actionBg:           '#0f172a',
      actionBorder:       '#1e293b',
      settingsBg:         '#0f172a',
      settingsBorder:     '#1e293b',
      settingsDivider:    '#162032',
      settingsLabel:      '#475569',
      scrollThumb:        '#334155',
      clockFaceFill:      '#0f172a',
      clockFaceStroke:    '#1e293b',
      clockTickMajor:     '#475569',
      clockTickMinor:     '#1e293b',
      clockHands:         '#cbd5e1',
      clockSecond:        '#38bdf8',
      clockCenter:        '#cbd5e1',
      noteDefaultBg:      '#162032',
      success:            '#34d399',
      info:               '#38bdf8',
    },
  },
  // ── New light themes ───────────────────────────────────────────────────────

  {
    id: 'mint',
    name: 'Mint',
    emoji: '🌿',
    dark: false,
    previewColors: ['#f0faf5', '#b8e8d0', '#10b981', '#064e3b'],
    background: { label: 'Fresh Mint', bg: '#f0faf5', dot: '#b8e8d0' },
    vars: {
      widgetBg:           '#f8fdfb',
      widgetBorder:       '#b8e8d0',
      widgetBorderActive: '#6dd4a8',
      shadowSm:           '0 1px 3px rgba(0,80,40,0.08)',
      shadowMd:           '0 4px 12px rgba(0,80,40,0.1)',
      shadowLg:           '0 20px 40px rgba(0,80,40,0.14)',
      backdropFilter:     'none',
      textPrimary:        '#064e3b',
      textMuted:          '#4a9a78',
      surfaceSubtle:      '#e0f5eb',
      surfaceHover:       '#c8eeda',
      surfaceDanger:      '#fff0ee',
      accent:             '#10b981',
      accentText:         '#ffffff',
      danger:             '#e03050',
      actionBg:           '#f8fdfb',
      actionBorder:       '#b8e8d0',
      settingsBg:         '#f8fdfb',
      settingsBorder:     '#b8e8d0',
      settingsDivider:    '#e0f5eb',
      settingsLabel:      '#4a9a78',
      scrollThumb:        '#6dd4a8',
      clockFaceFill:      '#f8fdfb',
      clockFaceStroke:    '#b8e8d0',
      clockTickMajor:     '#4a9a78',
      clockTickMinor:     '#b8e8d0',
      clockHands:         '#064e3b',
      clockSecond:        '#10b981',
      clockCenter:        '#064e3b',
      noteDefaultBg:      '#fefce8',
      success:            '#10b981',
      info:               '#06b6d4',
    },
  },

  {
    id: 'denim',
    name: 'Denim',
    emoji: '👖',
    dark: false,
    previewColors: ['#eff3f8', '#c5d5e8', '#3b6cb0', '#1a2d4a'],
    background: { label: 'Light Denim', bg: '#eff3f8', dot: '#c5d5e8' },
    vars: {
      widgetBg:           '#f5f8fc',
      widgetBorder:       '#c5d5e8',
      widgetBorderActive: '#7aa0cc',
      shadowSm:           '0 1px 3px rgba(20,40,80,0.08)',
      shadowMd:           '0 4px 12px rgba(20,40,80,0.1)',
      shadowLg:           '0 20px 40px rgba(20,40,80,0.14)',
      backdropFilter:     'none',
      textPrimary:        '#1a2d4a',
      textMuted:          '#5a7a9e',
      surfaceSubtle:      '#e4ecf6',
      surfaceHover:       '#d0deee',
      surfaceDanger:      '#fff0f0',
      accent:             '#3b6cb0',
      accentText:         '#ffffff',
      danger:             '#e03050',
      actionBg:           '#f5f8fc',
      actionBorder:       '#c5d5e8',
      settingsBg:         '#f5f8fc',
      settingsBorder:     '#c5d5e8',
      settingsDivider:    '#e4ecf6',
      settingsLabel:      '#5a7a9e',
      scrollThumb:        '#7aa0cc',
      clockFaceFill:      '#f5f8fc',
      clockFaceStroke:    '#c5d5e8',
      clockTickMajor:     '#5a7a9e',
      clockTickMinor:     '#c5d5e8',
      clockHands:         '#1a2d4a',
      clockSecond:        '#3b6cb0',
      clockCenter:        '#1a2d4a',
      noteDefaultBg:      '#fefce8',
      success:            '#22c55e',
      info:               '#3b6cb0',
    },
  },

  {
    id: 'rose-quartz',
    name: 'Rose',
    emoji: '🌸',
    dark: false,
    previewColors: ['#fdf0f3', '#f5c8d5', '#e05080', '#4a1828'],
    background: { label: 'Rose Quartz', bg: '#fdf0f3', dot: '#f5c8d5' },
    vars: {
      widgetBg:           '#fff5f7',
      widgetBorder:       '#f5c8d5',
      widgetBorderActive: '#e898b0',
      shadowSm:           '0 1px 3px rgba(120,20,50,0.08)',
      shadowMd:           '0 4px 12px rgba(120,20,50,0.1)',
      shadowLg:           '0 20px 40px rgba(120,20,50,0.14)',
      backdropFilter:     'none',
      textPrimary:        '#4a1828',
      textMuted:          '#a05070',
      surfaceSubtle:      '#fae0e6',
      surfaceHover:       '#f5ccd8',
      surfaceDanger:      '#fff0ee',
      accent:             '#e05080',
      accentText:         '#ffffff',
      danger:             '#c0392b',
      actionBg:           '#fff5f7',
      actionBorder:       '#f5c8d5',
      settingsBg:         '#fff5f7',
      settingsBorder:     '#f5c8d5',
      settingsDivider:    '#fae0e6',
      settingsLabel:      '#a05070',
      scrollThumb:        '#e898b0',
      clockFaceFill:      '#fff5f7',
      clockFaceStroke:    '#f5c8d5',
      clockTickMajor:     '#a05070',
      clockTickMinor:     '#f5c8d5',
      clockHands:         '#4a1828',
      clockSecond:        '#e05080',
      clockCenter:        '#4a1828',
      noteDefaultBg:      '#fefce8',
      success:            '#16a34a',
      info:               '#be185d',
    },
  },

  // ── New dark themes ────────────────────────────────────────────────────────

  {
    id: 'dracula',
    name: 'Dracula',
    emoji: '🧛',
    dark: true,
    previewColors: ['#282a36', '#44475a', '#bd93f9', '#f8f8f2'],
    background: { label: 'Dracula', bg: '#1e1f29', dot: '#282a36' },
    vars: {
      widgetBg:           '#282a36',
      widgetBorder:       '#44475a',
      widgetBorderActive: '#6272a4',
      shadowSm:           '0 1px 3px rgba(0,0,0,0.5)',
      shadowMd:           '0 4px 16px rgba(0,0,0,0.6)',
      shadowLg:           '0 20px 48px rgba(0,0,0,0.8)',
      backdropFilter:     'none',
      textPrimary:        '#f8f8f2',
      textMuted:          '#6272a4',
      surfaceSubtle:      '#1e1f29',
      surfaceHover:       '#383a4a',
      surfaceDanger:      '#3a1a1a',
      accent:             '#bd93f9',
      accentText:         '#282a36',
      danger:             '#ff5555',
      actionBg:           '#282a36',
      actionBorder:       '#44475a',
      settingsBg:         '#282a36',
      settingsBorder:     '#44475a',
      settingsDivider:    '#383a4a',
      settingsLabel:      '#6272a4',
      scrollThumb:        '#6272a4',
      clockFaceFill:      '#282a36',
      clockFaceStroke:    '#44475a',
      clockTickMajor:     '#6272a4',
      clockTickMinor:     '#44475a',
      clockHands:         '#f8f8f2',
      clockSecond:        '#ff79c6',
      clockCenter:        '#bd93f9',
      noteDefaultBg:      '#383a4a',
      success:            '#50fa7b',
      info:               '#8be9fd',
    },
  },

  {
    id: 'cobalt',
    name: 'Cobalt',
    emoji: '💙',
    dark: true,
    previewColors: ['#071020', '#0d1e38', '#00b4ff', '#c0e0ff'],
    background: { label: 'Deep Cobalt', bg: '#030a14', dot: '#0a1a2e' },
    vars: {
      widgetBg:           '#071020',
      widgetBorder:       '#0d1e38',
      widgetBorderActive: '#1a3a6a',
      shadowSm:           '0 1px 4px rgba(0,100,200,0.1)',
      shadowMd:           '0 4px 16px rgba(0,100,200,0.15)',
      shadowLg:           '0 20px 48px rgba(0,100,200,0.2)',
      backdropFilter:     'none',
      textPrimary:        '#c0e0ff',
      textMuted:          '#2a5a8a',
      surfaceSubtle:      '#030a14',
      surfaceHover:       '#0d1e38',
      surfaceDanger:      '#200810',
      accent:             '#00b4ff',
      accentText:         '#071020',
      danger:             '#ff4455',
      actionBg:           '#071020',
      actionBorder:       '#0d1e38',
      settingsBg:         '#071020',
      settingsBorder:     '#0d1e38',
      settingsDivider:    '#0d1e38',
      settingsLabel:      '#2a5a8a',
      scrollThumb:        '#1a3a6a',
      clockFaceFill:      '#071020',
      clockFaceStroke:    '#0d1e38',
      clockTickMajor:     '#2a5a8a',
      clockTickMinor:     '#0d1e38',
      clockHands:         '#c0e0ff',
      clockSecond:        '#00b4ff',
      clockCenter:        '#00b4ff',
      noteDefaultBg:      '#0d1e38',
      success:            '#00d084',
      info:               '#00b4ff',
    },
  },

  {
    id: 'copper',
    name: 'Copper',
    emoji: '🔶',
    dark: true,
    previewColors: ['#1a1208', '#2e2010', '#c87941', '#f0d8b0'],
    background: { label: 'Dark Copper', bg: '#100c08', dot: '#201810' },
    vars: {
      widgetBg:           '#1a1208',
      widgetBorder:       '#2e2010',
      widgetBorderActive: '#5a3820',
      shadowSm:           '0 1px 3px rgba(0,0,0,0.5)',
      shadowMd:           '0 4px 16px rgba(0,0,0,0.6)',
      shadowLg:           '0 20px 48px rgba(0,0,0,0.8)',
      backdropFilter:     'none',
      textPrimary:        '#f0d8b0',
      textMuted:          '#7a5535',
      surfaceSubtle:      '#100c08',
      surfaceHover:       '#241a0c',
      surfaceDanger:      '#280a08',
      accent:             '#c87941',
      accentText:         '#1a1208',
      danger:             '#ff4444',
      actionBg:           '#1a1208',
      actionBorder:       '#2e2010',
      settingsBg:         '#1a1208',
      settingsBorder:     '#2e2010',
      settingsDivider:    '#241a0c',
      settingsLabel:      '#7a5535',
      scrollThumb:        '#5a3820',
      clockFaceFill:      '#1a1208',
      clockFaceStroke:    '#2e2010',
      clockTickMajor:     '#7a5535',
      clockTickMinor:     '#2e2010',
      clockHands:         '#f0d8b0',
      clockSecond:        '#c87941',
      clockCenter:        '#c87941',
      noteDefaultBg:      '#241a0c',
      success:            '#a3724a',
      info:               '#c87941',
    },
  },

  // ── Duotone light themes ───────────────────────────────────────────────────

  {
    id: 'lavender-coral',
    name: 'Lav + Coral',
    emoji: '🪻',
    dark: false,
    previewColors: ['#f3f0ff', '#d8d0f8', '#f4614a', '#2d1a4a'],
    background: { label: 'Lavender', bg: '#f3f0ff', dot: '#d8d0f8' },
    vars: {
      widgetBg:           '#f9f7ff',
      widgetBorder:       '#d8d0f8',
      widgetBorderActive: '#b8a8f0',
      shadowSm:           '0 1px 3px rgba(60,20,120,0.08)',
      shadowMd:           '0 4px 12px rgba(60,20,120,0.1)',
      shadowLg:           '0 20px 40px rgba(60,20,120,0.14)',
      backdropFilter:     'none',
      textPrimary:        '#2d1a4a',
      textMuted:          '#7a60a8',
      surfaceSubtle:      '#ede8ff',
      surfaceHover:       '#ddd5f8',
      surfaceDanger:      '#fff0ee',
      accent:             '#f4614a',
      accentText:         '#ffffff',
      danger:             '#e03020',
      actionBg:           '#f9f7ff',
      actionBorder:       '#d8d0f8',
      settingsBg:         '#f9f7ff',
      settingsBorder:     '#d8d0f8',
      settingsDivider:    '#ede8ff',
      settingsLabel:      '#7a60a8',
      scrollThumb:        '#b8a8f0',
      clockFaceFill:      '#f9f7ff',
      clockFaceStroke:    '#d8d0f8',
      clockTickMajor:     '#7a60a8',
      clockTickMinor:     '#d8d0f8',
      clockHands:         '#2d1a4a',
      clockSecond:        '#f4614a',
      clockCenter:        '#2d1a4a',
      noteDefaultBg:      '#fff8e8',
      success:            '#7c3aed',
      info:               '#6d28d9',
    },
  },

  {
    id: 'sky-amber',
    name: 'Sky + Amber',
    emoji: '🌤️',
    dark: false,
    previewColors: ['#eef6ff', '#c0ddf8', '#d97706', '#0c2a4a'],
    background: { label: 'Sky Blue', bg: '#eef6ff', dot: '#c0ddf8' },
    vars: {
      widgetBg:           '#f5f9ff',
      widgetBorder:       '#c0ddf8',
      widgetBorderActive: '#80baf0',
      shadowSm:           '0 1px 3px rgba(0,40,100,0.08)',
      shadowMd:           '0 4px 12px rgba(0,40,100,0.1)',
      shadowLg:           '0 20px 40px rgba(0,40,100,0.14)',
      backdropFilter:     'none',
      textPrimary:        '#0c2a4a',
      textMuted:          '#4a7aaa',
      surfaceSubtle:      '#daeeff',
      surfaceHover:       '#c4e2f8',
      surfaceDanger:      '#fff0ee',
      accent:             '#d97706',
      accentText:         '#ffffff',
      danger:             '#e03020',
      actionBg:           '#f5f9ff',
      actionBorder:       '#c0ddf8',
      settingsBg:         '#f5f9ff',
      settingsBorder:     '#c0ddf8',
      settingsDivider:    '#daeeff',
      settingsLabel:      '#4a7aaa',
      scrollThumb:        '#80baf0',
      clockFaceFill:      '#f5f9ff',
      clockFaceStroke:    '#c0ddf8',
      clockTickMajor:     '#4a7aaa',
      clockTickMinor:     '#c0ddf8',
      clockHands:         '#0c2a4a',
      clockSecond:        '#d97706',
      clockCenter:        '#0c2a4a',
      noteDefaultBg:      '#fffbe8',
      success:            '#0c7a4a',
      info:               '#3b6cb0',
    },
  },

  {
    id: 'moss-rust',
    name: 'Moss + Rust',
    emoji: '🍂',
    dark: false,
    previewColors: ['#f0f4ee', '#c8d8c0', '#c0430a', '#1e2e18'],
    background: { label: 'Soft Moss', bg: '#f0f4ee', dot: '#c8d8c0' },
    vars: {
      widgetBg:           '#f6f9f4',
      widgetBorder:       '#c8d8c0',
      widgetBorderActive: '#90b880',
      shadowSm:           '0 1px 3px rgba(20,50,10,0.08)',
      shadowMd:           '0 4px 12px rgba(20,50,10,0.1)',
      shadowLg:           '0 20px 40px rgba(20,50,10,0.14)',
      backdropFilter:     'none',
      textPrimary:        '#1e2e18',
      textMuted:          '#5a7850',
      surfaceSubtle:      '#e4eee0',
      surfaceHover:       '#d4e4cc',
      surfaceDanger:      '#fff0ee',
      accent:             '#c0430a',
      accentText:         '#ffffff',
      danger:             '#c0390a',
      actionBg:           '#f6f9f4',
      actionBorder:       '#c8d8c0',
      settingsBg:         '#f6f9f4',
      settingsBorder:     '#c8d8c0',
      settingsDivider:    '#e4eee0',
      settingsLabel:      '#5a7850',
      scrollThumb:        '#90b880',
      clockFaceFill:      '#f6f9f4',
      clockFaceStroke:    '#c8d8c0',
      clockTickMajor:     '#5a7850',
      clockTickMinor:     '#c8d8c0',
      clockHands:         '#1e2e18',
      clockSecond:        '#c0430a',
      clockCenter:        '#1e2e18',
      noteDefaultBg:      '#fffbe8',
      success:            '#5a7850',
      info:               '#5a7850',
    },
  },

  // ── Duotone dark themes ────────────────────────────────────────────────────

  {
    id: 'navy-gold',
    name: 'Navy + Gold',
    emoji: '⚓',
    dark: true,
    previewColors: ['#080e1c', '#101c38', '#f0b429', '#d0e0ff'],
    background: { label: 'Deep Navy', bg: '#05080f', dot: '#0d1628' },
    vars: {
      widgetBg:           '#080e1c',
      widgetBorder:       '#101c38',
      widgetBorderActive: '#1e3460',
      shadowSm:           '0 1px 3px rgba(0,0,0,0.5)',
      shadowMd:           '0 4px 16px rgba(0,0,0,0.6)',
      shadowLg:           '0 20px 48px rgba(0,0,0,0.8)',
      backdropFilter:     'none',
      textPrimary:        '#d0e0ff',
      textMuted:          '#304880',
      surfaceSubtle:      '#05080f',
      surfaceHover:       '#101c38',
      surfaceDanger:      '#280a0a',
      accent:             '#f0b429',
      accentText:         '#080e1c',
      danger:             '#ff4444',
      actionBg:           '#080e1c',
      actionBorder:       '#101c38',
      settingsBg:         '#080e1c',
      settingsBorder:     '#101c38',
      settingsDivider:    '#101c38',
      settingsLabel:      '#304880',
      scrollThumb:        '#1e3460',
      clockFaceFill:      '#080e1c',
      clockFaceStroke:    '#101c38',
      clockTickMajor:     '#304880',
      clockTickMinor:     '#101c38',
      clockHands:         '#d0e0ff',
      clockSecond:        '#f0b429',
      clockCenter:        '#f0b429',
      noteDefaultBg:      '#101c38',
      success:            '#34d399',
      info:               '#60a5fa',
    },
  },

  {
    id: 'forest-pink',
    name: 'Forest + Pink',
    emoji: '🌲',
    dark: true,
    previewColors: ['#081208', '#102010', '#f472b6', '#d0f0d0'],
    background: { label: 'Deep Forest', bg: '#050d05', dot: '#0d1a0d' },
    vars: {
      widgetBg:           '#081208',
      widgetBorder:       '#102010',
      widgetBorderActive: '#1e401e',
      shadowSm:           '0 1px 3px rgba(0,0,0,0.5)',
      shadowMd:           '0 4px 16px rgba(0,0,0,0.6)',
      shadowLg:           '0 20px 48px rgba(0,0,0,0.8)',
      backdropFilter:     'none',
      textPrimary:        '#d0f0d0',
      textMuted:          '#2a5a2a',
      surfaceSubtle:      '#050d05',
      surfaceHover:       '#102010',
      surfaceDanger:      '#280a0a',
      accent:             '#f472b6',
      accentText:         '#081208',
      danger:             '#ff4444',
      actionBg:           '#081208',
      actionBorder:       '#102010',
      settingsBg:         '#081208',
      settingsBorder:     '#102010',
      settingsDivider:    '#102010',
      settingsLabel:      '#2a5a2a',
      scrollThumb:        '#1e401e',
      clockFaceFill:      '#081208',
      clockFaceStroke:    '#102010',
      clockTickMajor:     '#2a5a2a',
      clockTickMinor:     '#102010',
      clockHands:         '#d0f0d0',
      clockSecond:        '#f472b6',
      clockCenter:        '#f472b6',
      noteDefaultBg:      '#102010',
      success:            '#4ade80',
      info:               '#f472b6',
    },
  },

  {
    id: 'plum-cyan',
    name: 'Plum + Cyan',
    emoji: '🫐',
    dark: true,
    previewColors: ['#100818', '#1e1030', '#00e5cc', '#e0d0f8'],
    background: { label: 'Deep Plum', bg: '#0a0510', dot: '#160d28' },
    vars: {
      widgetBg:           '#100818',
      widgetBorder:       '#1e1030',
      widgetBorderActive: '#3a1a60',
      shadowSm:           '0 1px 3px rgba(0,0,0,0.5)',
      shadowMd:           '0 4px 16px rgba(0,0,0,0.6)',
      shadowLg:           '0 20px 48px rgba(0,0,0,0.8)',
      backdropFilter:     'none',
      textPrimary:        '#e0d0f8',
      textMuted:          '#5a3a80',
      surfaceSubtle:      '#0a0510',
      surfaceHover:       '#1e1030',
      surfaceDanger:      '#280a0a',
      accent:             '#00e5cc',
      accentText:         '#100818',
      danger:             '#ff4444',
      actionBg:           '#100818',
      actionBorder:       '#1e1030',
      settingsBg:         '#100818',
      settingsBorder:     '#1e1030',
      settingsDivider:    '#1e1030',
      settingsLabel:      '#5a3a80',
      scrollThumb:        '#3a1a60',
      clockFaceFill:      '#100818',
      clockFaceStroke:    '#1e1030',
      clockTickMajor:     '#5a3a80',
      clockTickMinor:     '#1e1030',
      clockHands:         '#e0d0f8',
      clockSecond:        '#00e5cc',
      clockCenter:        '#00e5cc',
      noteDefaultBg:      '#1e1030',
      success:            '#00e5cc',
      info:               '#818cf8',
    },
  },

  {
    id: 'charcoal-lime',
    name: 'Char + Lime',
    emoji: '⚡',
    dark: true,
    previewColors: ['#141410', '#242420', '#a3e635', '#e8e8d8'],
    background: { label: 'Warm Charcoal', bg: '#0e0e0a', dot: '#1c1c16' },
    vars: {
      widgetBg:           '#141410',
      widgetBorder:       '#242420',
      widgetBorderActive: '#3a3a30',
      shadowSm:           '0 1px 3px rgba(0,0,0,0.5)',
      shadowMd:           '0 4px 16px rgba(0,0,0,0.6)',
      shadowLg:           '0 20px 48px rgba(0,0,0,0.8)',
      backdropFilter:     'none',
      textPrimary:        '#e8e8d8',
      textMuted:          '#4a4a38',
      surfaceSubtle:      '#0e0e0a',
      surfaceHover:       '#1e1e18',
      surfaceDanger:      '#280808',
      accent:             '#a3e635',
      accentText:         '#141410',
      danger:             '#ff4444',
      actionBg:           '#141410',
      actionBorder:       '#242420',
      settingsBg:         '#141410',
      settingsBorder:     '#242420',
      settingsDivider:    '#1e1e18',
      settingsLabel:      '#4a4a38',
      scrollThumb:        '#3a3a30',
      clockFaceFill:      '#141410',
      clockFaceStroke:    '#242420',
      clockTickMajor:     '#4a4a38',
      clockTickMinor:     '#242420',
      clockHands:         '#e8e8d8',
      clockSecond:        '#a3e635',
      clockCenter:        '#a3e635',
      noteDefaultBg:      '#1e1e18',
      success:            '#a3e635',
      info:               '#84cc16',
    },
  },

  // ── New themes ─────────────────────────────────────────────────────────────

  {
    id: 'sunset',
    name: 'Sunset',
    emoji: '🌇',
    dark: false,
    previewColors: ['#fff3e8', '#f4c9a0', '#e8640a', '#3d1f0a'],
    background: { label: 'Warm Sand', bg: '#fff3e8', dot: '#f4c9a0' },
    vars: {
      widgetBg:           '#fff8f2',
      widgetBorder:       '#f4c9a0',
      widgetBorderActive: '#e8a060',
      shadowSm:           '0 1px 3px rgba(120,60,0,0.08)',
      shadowMd:           '0 4px 12px rgba(120,60,0,0.12)',
      shadowLg:           '0 20px 40px rgba(120,60,0,0.16)',
      backdropFilter:     'none',
      textPrimary:        '#3d1f0a',
      textMuted:          '#a07050',
      surfaceSubtle:      '#fef0e2',
      surfaceHover:       '#f8dfc8',
      surfaceDanger:      '#fff0ee',
      accent:             '#e8640a',
      accentText:         '#ffffff',
      danger:             '#e03030',
      actionBg:           '#fff8f2',
      actionBorder:       '#f4c9a0',
      settingsBg:         '#fff8f2',
      settingsBorder:     '#f4c9a0',
      settingsDivider:    '#fef0e2',
      settingsLabel:      '#a07050',
      scrollThumb:        '#e8a060',
      clockFaceFill:      '#fff8f2',
      clockFaceStroke:    '#f4c9a0',
      clockTickMajor:     '#a07050',
      clockTickMinor:     '#f4c9a0',
      clockHands:         '#3d1f0a',
      clockSecond:        '#e8640a',
      clockCenter:        '#3d1f0a',
      noteDefaultBg:      '#fff3c8',
      success:            '#15803d',
      info:               '#b45309',
    },
  },

  {
    id: 'midnight-rose',
    name: 'Midnight Rose',
    emoji: '🌹',
    dark: true,
    previewColors: ['#130a10', '#2d1a28', '#e879a0', '#f0d0e0'],
    background: { label: 'Deep Rose', bg: '#0d0709', dot: '#1e0e18' },
    vars: {
      widgetBg:           '#170f1c',
      widgetBorder:       '#2d1a35',
      widgetBorderActive: '#5a2a50',
      shadowSm:           '0 1px 3px rgba(0,0,0,0.5)',
      shadowMd:           '0 4px 16px rgba(0,0,0,0.6)',
      shadowLg:           '0 20px 48px rgba(0,0,0,0.8)',
      backdropFilter:     'none',
      textPrimary:        '#f0d0e0',
      textMuted:          '#7a4a65',
      surfaceSubtle:      '#0d0709',
      surfaceHover:       '#22122a',
      surfaceDanger:      '#2a0e18',
      accent:             '#e879a0',
      accentText:         '#170f1c',
      danger:             '#f87171',
      actionBg:           '#170f1c',
      actionBorder:       '#2d1a35',
      settingsBg:         '#170f1c',
      settingsBorder:     '#2d1a35',
      settingsDivider:    '#22122a',
      settingsLabel:      '#7a4a65',
      scrollThumb:        '#5a2a50',
      clockFaceFill:      '#170f1c',
      clockFaceStroke:    '#2d1a35',
      clockTickMajor:     '#7a4a65',
      clockTickMinor:     '#2d1a35',
      clockHands:         '#f0d0e0',
      clockSecond:        '#e879a0',
      clockCenter:        '#f0d0e0',
      noteDefaultBg:      '#22122a',
      success:            '#e879a0',
      info:               '#c084fc',
    },
  },

  {
    id: 'arctic',
    name: 'Arctic',
    emoji: '❄️',
    dark: false,
    previewColors: ['#eaf4ff', '#b8d8f4', '#0077cc', '#082040'],
    background: { label: 'Ice Blue', bg: '#eaf4ff', dot: '#b8d8f4' },
    vars: {
      widgetBg:           '#f4f9ff',
      widgetBorder:       '#b8d8f4',
      widgetBorderActive: '#70b0e0',
      shadowSm:           '0 1px 3px rgba(0,60,120,0.08)',
      shadowMd:           '0 4px 12px rgba(0,60,120,0.1)',
      shadowLg:           '0 20px 40px rgba(0,60,120,0.14)',
      backdropFilter:     'none',
      textPrimary:        '#082040',
      textMuted:          '#5090b8',
      surfaceSubtle:      '#e0f0ff',
      surfaceHover:       '#c8e4f8',
      surfaceDanger:      '#fff0f0',
      accent:             '#0077cc',
      accentText:         '#ffffff',
      danger:             '#e03050',
      actionBg:           '#f4f9ff',
      actionBorder:       '#b8d8f4',
      settingsBg:         '#f4f9ff',
      settingsBorder:     '#b8d8f4',
      settingsDivider:    '#e0f0ff',
      settingsLabel:      '#5090b8',
      scrollThumb:        '#70b0e0',
      clockFaceFill:      '#f4f9ff',
      clockFaceStroke:    '#b8d8f4',
      clockTickMajor:     '#5090b8',
      clockTickMinor:     '#b8d8f4',
      clockHands:         '#082040',
      clockSecond:        '#0077cc',
      clockCenter:        '#082040',
      noteDefaultBg:      '#fffde8',
      success:            '#0e7a5e',
      info:               '#0077cc',
    },
  },

  {
    id: 'volcanic',
    name: 'Volcanic',
    emoji: '🌋',
    dark: true,
    previewColors: ['#110604', '#2a1008', '#ff5733', '#ffd0c0'],
    background: { label: 'Ash Black', bg: '#0c0402', dot: '#1e0c08' },
    vars: {
      widgetBg:           '#1a0e0a',
      widgetBorder:       '#3a1a10',
      widgetBorderActive: '#6a2a18',
      shadowSm:           '0 1px 3px rgba(0,0,0,0.5)',
      shadowMd:           '0 4px 16px rgba(0,0,0,0.6)',
      shadowLg:           '0 20px 48px rgba(0,0,0,0.8)',
      backdropFilter:     'none',
      textPrimary:        '#ffd0c0',
      textMuted:          '#7a4030',
      surfaceSubtle:      '#0c0402',
      surfaceHover:       '#2a1208',
      surfaceDanger:      '#2a0808',
      accent:             '#ff5733',
      accentText:         '#ffffff',
      danger:             '#ff3333',
      actionBg:           '#1a0e0a',
      actionBorder:       '#3a1a10',
      settingsBg:         '#1a0e0a',
      settingsBorder:     '#3a1a10',
      settingsDivider:    '#2a1208',
      settingsLabel:      '#7a4030',
      scrollThumb:        '#6a2a18',
      clockFaceFill:      '#1a0e0a',
      clockFaceStroke:    '#3a1a10',
      clockTickMajor:     '#7a4030',
      clockTickMinor:     '#3a1a10',
      clockHands:         '#ffd0c0',
      clockSecond:        '#ff5733',
      clockCenter:        '#ffd0c0',
      noteDefaultBg:      '#2a1208',
      success:            '#ff5733',
      info:               '#f0a060',
    },
  },

  {
    id: 'cream',
    name: 'Cream',
    emoji: '🍦',
    dark: false,
    previewColors: ['#f5efe6', '#e0d5c5', '#8b6914', '#2d2010'],
    background: { label: 'Warm Cream', bg: '#f5efe6', dot: '#e0d5c5' },
    vars: {
      widgetBg:           '#faf6f0',
      widgetBorder:       '#e0d5c5',
      widgetBorderActive: '#c8b89a',
      shadowSm:           '0 1px 3px rgba(60,40,0,0.08)',
      shadowMd:           '0 4px 12px rgba(60,40,0,0.1)',
      shadowLg:           '0 20px 40px rgba(60,40,0,0.14)',
      backdropFilter:     'none',
      textPrimary:        '#2d2010',
      textMuted:          '#8b7355',
      surfaceSubtle:      '#f0e8da',
      surfaceHover:       '#e5d8c5',
      surfaceDanger:      '#fff0ee',
      accent:             '#8b6914',
      accentText:         '#ffffff',
      danger:             '#c0392b',
      actionBg:           '#faf6f0',
      actionBorder:       '#e0d5c5',
      settingsBg:         '#faf6f0',
      settingsBorder:     '#e0d5c5',
      settingsDivider:    '#f0e8da',
      settingsLabel:      '#8b7355',
      scrollThumb:        '#c8b89a',
      clockFaceFill:      '#faf6f0',
      clockFaceStroke:    '#e0d5c5',
      clockTickMajor:     '#8b7355',
      clockTickMinor:     '#e0d5c5',
      clockHands:         '#2d2010',
      clockSecond:        '#8b6914',
      clockCenter:        '#2d2010',
      noteDefaultBg:      '#fffde0',
      success:            '#4a7c3f',
      info:               '#8b6914',
    },
  },

  {
    id: 'neon-green',
    name: 'Neon Green',
    emoji: '💚',
    dark: true,
    previewColors: ['#020f02', '#0a2a0a', '#39ff14', '#ccffcc'],
    background: { label: 'Deep Black', bg: '#010801', dot: '#082008' },
    vars: {
      widgetBg:           '#040f04',
      widgetBorder:       '#0a2a0a',
      widgetBorderActive: '#1a5a1a',
      shadowSm:           '0 1px 4px rgba(0,255,20,0.08)',
      shadowMd:           '0 4px 16px rgba(0,255,20,0.1)',
      shadowLg:           '0 20px 48px rgba(0,255,20,0.15)',
      backdropFilter:     'none',
      textPrimary:        '#ccffcc',
      textMuted:          '#2a6a2a',
      surfaceSubtle:      '#010801',
      surfaceHover:       '#0a200a',
      surfaceDanger:      '#200808',
      accent:             '#39ff14',
      accentText:         '#010801',
      danger:             '#ff3333',
      actionBg:           '#040f04',
      actionBorder:       '#0a2a0a',
      settingsBg:         '#040f04',
      settingsBorder:     '#0a2a0a',
      settingsDivider:    '#0a200a',
      settingsLabel:      '#2a6a2a',
      scrollThumb:        '#1a5a1a',
      clockFaceFill:      '#040f04',
      clockFaceStroke:    '#0a2a0a',
      clockTickMajor:     '#2a6a2a',
      clockTickMinor:     '#0a2a0a',
      clockHands:         '#ccffcc',
      clockSecond:        '#39ff14',
      clockCenter:        '#39ff14',
      noteDefaultBg:      '#0a200a',
      success:            '#39ff14',
      info:               '#00e5cc',
    },
  },
]

export const THEME_MAP = Object.fromEntries(THEMES.map((t) => [t.id, t]))

export const CSS_VAR_MAP: Record<keyof ThemeVars, string> = {
  widgetBg:           '--wt-bg',
  widgetBorder:       '--wt-border',
  widgetBorderActive: '--wt-border-active',
  shadowSm:           '--wt-shadow-sm',
  shadowMd:           '--wt-shadow-md',
  shadowLg:           '--wt-shadow-lg',
  backdropFilter:     '--wt-backdrop',
  textPrimary:        '--wt-text',
  textMuted:          '--wt-text-muted',
  surfaceSubtle:      '--wt-surface',
  surfaceHover:       '--wt-surface-hover',
  surfaceDanger:      '--wt-surface-danger',
  accent:             '--wt-accent',
  accentText:         '--wt-accent-text',
  danger:             '--wt-danger',
  actionBg:           '--wt-action-bg',
  actionBorder:       '--wt-action-border',
  settingsBg:         '--wt-settings-bg',
  settingsBorder:     '--wt-settings-border',
  settingsDivider:    '--wt-settings-divider',
  settingsLabel:      '--wt-settings-label',
  scrollThumb:        '--wt-scroll-thumb',
  clockFaceFill:      '--wt-clock-face',
  clockFaceStroke:    '--wt-clock-stroke',
  clockTickMajor:     '--wt-clock-tick-major',
  clockTickMinor:     '--wt-clock-tick-minor',
  clockHands:         '--wt-clock-hands',
  clockSecond:        '--wt-clock-second',
  clockCenter:        '--wt-clock-center',
  noteDefaultBg:      '--wt-note-bg',
  success:            '--wt-success',
  info:               '--wt-info',
}

export function applyThemeVars(vars: ThemeVars) {
  const root = document.documentElement
  root.classList.add('theme-transitioning')
  for (const [key, cssVar] of Object.entries(CSS_VAR_MAP)) {
    root.style.setProperty(cssVar, vars[key as keyof ThemeVars])
  }
  setTimeout(() => root.classList.remove('theme-transitioning'), 450)
}
