// ── Theme system ─────────────────────────────────────────────────────────────
//
// All widget colors are driven by CSS custom properties (--wt-*).
// Themes define the full set of vars. The active theme + any custom overrides
// are applied to :root by the theme store applier.
//
// Each theme also carries a `background` that is applied to the whiteboard
// canvas whenever the user picks that theme.

import { type Background } from '../constants/backgrounds'

export interface ThemeVars {
  // Widget frame
  widgetBg:           string
  widgetBorder:       string
  widgetBorderActive: string
  shadowSm:           string
  shadowMd:           string
  shadowLg:           string
  backdropFilter:     string

  // Text
  textPrimary: string
  textMuted:   string

  // Surfaces
  surfaceSubtle: string
  surfaceHover:  string
  surfaceDanger: string

  // Accent + danger
  accent:      string
  accentText:  string
  danger:      string

  // Action panel (floating controls)
  actionBg:     string
  actionBorder: string

  // Settings panel
  settingsBg:      string
  settingsBorder:  string
  settingsDivider: string
  settingsLabel:   string
  scrollThumb:     string

  // Clock widget
  clockFaceFill:   string
  clockFaceStroke: string
  clockTickMajor:  string
  clockTickMinor:  string
  clockHands:      string
  clockSecond:     string
  clockCenter:     string

  // Note widget
  noteDefaultBg: string
}

export interface Theme {
  id:            string
  name:          string
  emoji:         string
  dark:          boolean
  previewColors: [string, string, string, string]  // bg, border, accent, text
  background:    Background
  vars:          ThemeVars
}

// ── CSS var map ───────────────────────────────────────────────────────────────

export const VAR_LABELS: Partial<Record<keyof ThemeVars, string>> = {
  widgetBg:           'Widget Background',
  widgetBorder:       'Border',
  widgetBorderActive: 'Border (Active)',
  textPrimary:        'Text',
  textMuted:          'Text Muted',
  surfaceHover:       'Hover Surface',
  accent:             'Accent Color',
  danger:             'Danger Color',
  actionBg:           'Action Panel BG',
  clockFaceFill:      'Clock Face',
  clockHands:         'Clock Hands',
  clockSecond:        'Clock Second Hand',
  noteDefaultBg:      'Note Default BG',
}

// ── Preset themes ─────────────────────────────────────────────────────────────
// Light themes first, then dark themes

export const THEMES: Theme[] = [
  // ── Light ─────────────────────────────────────────────────────────────────
  {
    id: 'minimal',
    name: 'Minimal',
    emoji: '○',
    dark: false,
    previewColors: ['#ffffff', '#e7e5e4', '#3b82f6', '#1c1917'],
    background: { label: 'White', bg: '#ffffff', dot: '#e2e8f0' },
    vars: {
      widgetBg:           '#ffffff',
      widgetBorder:       '#e7e5e4',
      widgetBorderActive: '#d6d3d1',
      shadowSm:           '0 1px 3px rgba(0,0,0,0.08), 0 1px 2px rgba(0,0,0,0.05)',
      shadowMd:           '0 4px 12px rgba(0,0,0,0.1), 0 2px 4px rgba(0,0,0,0.06)',
      shadowLg:           '0 20px 40px rgba(0,0,0,0.15), 0 8px 16px rgba(0,0,0,0.08)',
      backdropFilter:     'none',
      textPrimary:        '#1c1917',
      textMuted:          '#a8a29e',
      surfaceSubtle:      '#fafaf9',
      surfaceHover:       '#f5f5f4',
      surfaceDanger:      '#fef2f2',
      accent:             '#3b82f6',
      accentText:         '#ffffff',
      danger:             '#f87171',
      actionBg:           '#ffffff',
      actionBorder:       '#e7e5e4',
      settingsBg:         '#ffffff',
      settingsBorder:     '#e7e5e4',
      settingsDivider:    '#f5f5f4',
      settingsLabel:      '#a8a29e',
      scrollThumb:        '#d6d3d1',
      clockFaceFill:      '#ffffff',
      clockFaceStroke:    '#e7e5e4',
      clockTickMajor:     '#a8a29e',
      clockTickMinor:     '#d6d3d1',
      clockHands:         '#1c1917',
      clockSecond:        '#ef4444',
      clockCenter:        '#1c1917',
      noteDefaultBg:      '#fef9c3',
    },
  },
  {
    id: 'slate',
    name: 'Slate',
    emoji: '▣',
    dark: false,
    previewColors: ['#f8fafc', '#cbd5e1', '#3b82f6', '#0f172a'],
    background: { label: 'Slate', bg: '#f1f5f9', dot: '#cbd5e1' },
    vars: {
      widgetBg:           '#f8fafc',
      widgetBorder:       '#cbd5e1',
      widgetBorderActive: '#94a3b8',
      shadowSm:           '0 1px 3px rgba(15,23,42,0.07)',
      shadowMd:           '0 4px 12px rgba(15,23,42,0.1)',
      shadowLg:           '0 20px 40px rgba(15,23,42,0.14)',
      backdropFilter:     'none',
      textPrimary:        '#0f172a',
      textMuted:          '#94a3b8',
      surfaceSubtle:      '#f1f5f9',
      surfaceHover:       '#e2e8f0',
      surfaceDanger:      '#fef2f2',
      accent:             '#3b82f6',
      accentText:         '#ffffff',
      danger:             '#ef4444',
      actionBg:           '#f8fafc',
      actionBorder:       '#cbd5e1',
      settingsBg:         '#f8fafc',
      settingsBorder:     '#cbd5e1',
      settingsDivider:    '#e2e8f0',
      settingsLabel:      '#94a3b8',
      scrollThumb:        '#cbd5e1',
      clockFaceFill:      '#f8fafc',
      clockFaceStroke:    '#cbd5e1',
      clockTickMajor:     '#94a3b8',
      clockTickMinor:     '#cbd5e1',
      clockHands:         '#0f172a',
      clockSecond:        '#3b82f6',
      clockCenter:        '#0f172a',
      noteDefaultBg:      '#f1f5f9',
    },
  },
  {
    id: 'paper',
    name: 'Paper',
    emoji: '▪',
    dark: false,
    previewColors: ['#faf8f5', '#e0d8cc', '#5c4a32', '#2d2016'],
    background: { label: 'Parchment', bg: '#f5f0eb', dot: '#c9bfb5' },
    vars: {
      widgetBg:           '#faf8f5',
      widgetBorder:       '#e0d8cc',
      widgetBorderActive: '#c9bfb5',
      shadowSm:           '0 1px 3px rgba(80,60,30,0.08)',
      shadowMd:           '0 4px 12px rgba(80,60,30,0.1)',
      shadowLg:           '0 20px 40px rgba(80,60,30,0.14)',
      backdropFilter:     'none',
      textPrimary:        '#2d2016',
      textMuted:          '#a0897a',
      surfaceSubtle:      '#f5f0eb',
      surfaceHover:       '#ede5d8',
      surfaceDanger:      '#fef2f2',
      accent:             '#5c4a32',
      accentText:         '#faf8f5',
      danger:             '#c0392b',
      actionBg:           '#faf8f5',
      actionBorder:       '#e0d8cc',
      settingsBg:         '#faf8f5',
      settingsBorder:     '#e0d8cc',
      settingsDivider:    '#ede5d8',
      settingsLabel:      '#a0897a',
      scrollThumb:        '#c9bfb5',
      clockFaceFill:      '#faf8f5',
      clockFaceStroke:    '#e0d8cc',
      clockTickMajor:     '#a0897a',
      clockTickMinor:     '#c9bfb5',
      clockHands:         '#2d2016',
      clockSecond:        '#8b4513',
      clockCenter:        '#2d2016',
      noteDefaultBg:      '#fef9e7',
    },
  },
  {
    id: 'amber',
    name: 'Amber',
    emoji: '◇',
    dark: false,
    previewColors: ['#fffbeb', '#fde68a', '#d97706', '#451a03'],
    background: { label: 'Sand', bg: '#fdf6e3', dot: '#d4c5a9' },
    vars: {
      widgetBg:           '#fffbeb',
      widgetBorder:       '#fde68a',
      widgetBorderActive: '#fbbf24',
      shadowSm:           '0 1px 3px rgba(180,120,0,0.08)',
      shadowMd:           '0 4px 12px rgba(180,120,0,0.12)',
      shadowLg:           '0 20px 40px rgba(180,120,0,0.16)',
      backdropFilter:     'none',
      textPrimary:        '#451a03',
      textMuted:          '#d97706',
      surfaceSubtle:      '#fef3c7',
      surfaceHover:       '#fde68a',
      surfaceDanger:      '#fef2f2',
      accent:             '#d97706',
      accentText:         '#ffffff',
      danger:             '#ef4444',
      actionBg:           '#fffbeb',
      actionBorder:       '#fde68a',
      settingsBg:         '#fffbeb',
      settingsBorder:     '#fde68a',
      settingsDivider:    '#fef3c7',
      settingsLabel:      '#b45309',
      scrollThumb:        '#fbbf24',
      clockFaceFill:      '#fffbeb',
      clockFaceStroke:    '#fde68a',
      clockTickMajor:     '#d97706',
      clockTickMinor:     '#fde68a',
      clockHands:         '#451a03',
      clockSecond:        '#d97706',
      clockCenter:        '#451a03',
      noteDefaultBg:      '#fef3c7',
    },
  },
  {
    id: 'rose',
    name: 'Rose',
    emoji: '◈',
    dark: false,
    previewColors: ['#fff5f7', '#fecdd3', '#e11d48', '#4c0519'],
    background: { label: 'Blush', bg: '#fff0f3', dot: '#fecdd3' },
    vars: {
      widgetBg:           '#fff5f7',
      widgetBorder:       '#fecdd3',
      widgetBorderActive: '#fda4af',
      shadowSm:           '0 1px 3px rgba(225,29,72,0.07)',
      shadowMd:           '0 4px 12px rgba(225,29,72,0.09)',
      shadowLg:           '0 20px 40px rgba(225,29,72,0.13)',
      backdropFilter:     'none',
      textPrimary:        '#4c0519',
      textMuted:          '#fb7185',
      surfaceSubtle:      '#fff1f2',
      surfaceHover:       '#ffe4e6',
      surfaceDanger:      '#ffe4e6',
      accent:             '#e11d48',
      accentText:         '#ffffff',
      danger:             '#e11d48',
      actionBg:           '#fff5f7',
      actionBorder:       '#fecdd3',
      settingsBg:         '#fff5f7',
      settingsBorder:     '#fecdd3',
      settingsDivider:    '#ffe4e6',
      settingsLabel:      '#fda4af',
      scrollThumb:        '#fda4af',
      clockFaceFill:      '#fff5f7',
      clockFaceStroke:    '#fecdd3',
      clockTickMajor:     '#fda4af',
      clockTickMinor:     '#fecdd3',
      clockHands:         '#4c0519',
      clockSecond:        '#e11d48',
      clockCenter:        '#4c0519',
      noteDefaultBg:      '#fff1f2',
    },
  },
  {
    id: 'glass',
    name: 'Glass',
    emoji: '◎',
    dark: false,
    previewColors: ['rgba(255,255,255,0.72)', 'rgba(255,255,255,0.45)', '#6366f1', '#1c1917'],
    background: { label: 'Lavender', bg: '#f5f0ff', dot: '#ddd6fe' },
    vars: {
      widgetBg:           'rgba(255,255,255,0.72)',
      widgetBorder:       'rgba(255,255,255,0.5)',
      widgetBorderActive: 'rgba(255,255,255,0.85)',
      shadowSm:           '0 2px 8px rgba(0,0,0,0.08), inset 0 1px 0 rgba(255,255,255,0.6)',
      shadowMd:           '0 8px 24px rgba(0,0,0,0.1), inset 0 1px 0 rgba(255,255,255,0.7)',
      shadowLg:           '0 24px 48px rgba(0,0,0,0.14), inset 0 1px 0 rgba(255,255,255,0.7)',
      backdropFilter:     'blur(14px) saturate(1.6)',
      textPrimary:        '#1c1917',
      textMuted:          '#78716c',
      surfaceSubtle:      'rgba(255,255,255,0.3)',
      surfaceHover:       'rgba(255,255,255,0.55)',
      surfaceDanger:      'rgba(254,242,242,0.8)',
      accent:             '#6366f1',
      accentText:         '#ffffff',
      danger:             '#ef4444',
      actionBg:           'rgba(255,255,255,0.82)',
      actionBorder:       'rgba(255,255,255,0.55)',
      settingsBg:         'rgba(255,255,255,0.88)',
      settingsBorder:     'rgba(255,255,255,0.5)',
      settingsDivider:    'rgba(255,255,255,0.35)',
      settingsLabel:      '#78716c',
      scrollThumb:        'rgba(100,100,100,0.25)',
      clockFaceFill:      'rgba(255,255,255,0.6)',
      clockFaceStroke:    'rgba(200,200,200,0.5)',
      clockTickMajor:     'rgba(100,100,100,0.55)',
      clockTickMinor:     'rgba(150,150,150,0.35)',
      clockHands:         '#1c1917',
      clockSecond:        '#6366f1',
      clockCenter:        '#1c1917',
      noteDefaultBg:      'rgba(255,249,195,0.75)',
    },
  },
  {
    id: 'sage',
    name: 'Sage',
    emoji: '◆',
    dark: false,
    previewColors: ['#f4f7f4', '#c6d6c6', '#4a7c59', '#1a2e1a'],
    background: { label: 'Meadow', bg: '#edf2ed', dot: '#c6d6c6' },
    vars: {
      widgetBg:           '#f4f7f4',
      widgetBorder:       '#c6d6c6',
      widgetBorderActive: '#8fad8f',
      shadowSm:           '0 1px 3px rgba(30,60,30,0.07)',
      shadowMd:           '0 4px 12px rgba(30,60,30,0.1)',
      shadowLg:           '0 20px 40px rgba(30,60,30,0.14)',
      backdropFilter:     'none',
      textPrimary:        '#1a2e1a',
      textMuted:          '#8fad8f',
      surfaceSubtle:      '#edf2ed',
      surfaceHover:       '#ddeadd',
      surfaceDanger:      '#fef2f2',
      accent:             '#4a7c59',
      accentText:         '#ffffff',
      danger:             '#ef4444',
      actionBg:           '#f4f7f4',
      actionBorder:       '#c6d6c6',
      settingsBg:         '#f4f7f4',
      settingsBorder:     '#c6d6c6',
      settingsDivider:    '#ddeadd',
      settingsLabel:      '#8fad8f',
      scrollThumb:        '#c6d6c6',
      clockFaceFill:      '#f4f7f4',
      clockFaceStroke:    '#c6d6c6',
      clockTickMajor:     '#8fad8f',
      clockTickMinor:     '#c6d6c6',
      clockHands:         '#1a2e1a',
      clockSecond:        '#4a7c59',
      clockCenter:        '#1a2e1a',
      noteDefaultBg:      '#ddeadd',
    },
  },
  // ── Dark ──────────────────────────────────────────────────────────────────
  {
    id: 'midnight',
    name: 'Midnight',
    emoji: '◉',
    dark: true,
    previewColors: ['#141414', '#2a2a2a', '#a3a3a3', '#f5f5f5'],
    background: { label: 'Charcoal', bg: '#1a1a1a', dot: '#2d2d2d' },
    vars: {
      widgetBg:           '#141414',
      widgetBorder:       '#2a2a2a',
      widgetBorderActive: '#3d3d3d',
      shadowSm:           '0 1px 3px rgba(0,0,0,0.5)',
      shadowMd:           '0 4px 16px rgba(0,0,0,0.6)',
      shadowLg:           '0 20px 48px rgba(0,0,0,0.8)',
      backdropFilter:     'none',
      textPrimary:        '#f5f5f5',
      textMuted:          '#737373',
      surfaceSubtle:      '#1a1a1a',
      surfaceHover:       '#262626',
      surfaceDanger:      '#2a1515',
      accent:             '#a3a3a3',
      accentText:         '#000000',
      danger:             '#f87171',
      actionBg:           '#1a1a1a',
      actionBorder:       '#2a2a2a',
      settingsBg:         '#1a1a1a',
      settingsBorder:     '#2a2a2a',
      settingsDivider:    '#222222',
      settingsLabel:      '#525252',
      scrollThumb:        '#404040',
      clockFaceFill:      '#1a1a1a',
      clockFaceStroke:    '#2a2a2a',
      clockTickMajor:     '#525252',
      clockTickMinor:     '#333333',
      clockHands:         '#e5e5e5',
      clockSecond:        '#f87171',
      clockCenter:        '#e5e5e5',
      noteDefaultBg:      '#262626',
    },
  },
  {
    id: 'stark',
    name: 'Stark',
    emoji: '⬡',
    dark: true,
    previewColors: ['#070c14', '#1a4a70', '#00b4ff', '#c8e8ff'],
    background: { label: 'Abyss', bg: '#070c14', dot: '#0d2035' },
    vars: {
      widgetBg:           '#070c14',
      widgetBorder:       '#0d2035',
      widgetBorderActive: '#1a4a70',
      shadowSm:           '0 1px 4px rgba(0,180,255,0.1)',
      shadowMd:           '0 4px 16px rgba(0,180,255,0.15)',
      shadowLg:           '0 20px 48px rgba(0,180,255,0.2), 0 0 0 1px rgba(0,180,255,0.05)',
      backdropFilter:     'none',
      textPrimary:        '#c8e8ff',
      textMuted:          '#4a7a9b',
      surfaceSubtle:      '#0a1520',
      surfaceHover:       '#0d2035',
      surfaceDanger:      '#1f0a0a',
      accent:             '#00b4ff',
      accentText:         '#000a14',
      danger:             '#ff4444',
      actionBg:           '#0a1520',
      actionBorder:       '#1a4a70',
      settingsBg:         '#0a1520',
      settingsBorder:     '#1a4a70',
      settingsDivider:    '#0d2035',
      settingsLabel:      '#4a7a9b',
      scrollThumb:        '#1a4a70',
      clockFaceFill:      '#070c14',
      clockFaceStroke:    '#1a4a70',
      clockTickMajor:     '#1a6080',
      clockTickMinor:     '#0d2a40',
      clockHands:         '#00b4ff',
      clockSecond:        '#ff4444',
      clockCenter:        '#00b4ff',
      noteDefaultBg:      '#0a1520',
    },
  },
  {
    id: 'forest',
    name: 'Forest',
    emoji: '◆',
    dark: true,
    previewColors: ['#0f1a0f', '#1a3a1a', '#22c55e', '#d4f5d4'],
    background: { label: 'Deep Forest', bg: '#0a150a', dot: '#162616' },
    vars: {
      widgetBg:           '#0f1a0f',
      widgetBorder:       '#1a3a1a',
      widgetBorderActive: '#2a5a2a',
      shadowSm:           '0 1px 3px rgba(0,0,0,0.5)',
      shadowMd:           '0 4px 16px rgba(0,80,0,0.2)',
      shadowLg:           '0 20px 48px rgba(0,80,0,0.3)',
      backdropFilter:     'none',
      textPrimary:        '#d4f5d4',
      textMuted:          '#4a7a4a',
      surfaceSubtle:      '#0d180d',
      surfaceHover:       '#162616',
      surfaceDanger:      '#1a0f0f',
      accent:             '#22c55e',
      accentText:         '#0a150a',
      danger:             '#f87171',
      actionBg:           '#0d180d',
      actionBorder:       '#1a3a1a',
      settingsBg:         '#0d180d',
      settingsBorder:     '#1a3a1a',
      settingsDivider:    '#141f14',
      settingsLabel:      '#3a6a3a',
      scrollThumb:        '#2a5a2a',
      clockFaceFill:      '#0f1a0f',
      clockFaceStroke:    '#1a3a1a',
      clockTickMajor:     '#2a5a2a',
      clockTickMinor:     '#1a3a1a',
      clockHands:         '#a3e8a3',
      clockSecond:        '#22c55e',
      clockCenter:        '#a3e8a3',
      noteDefaultBg:      '#0d180d',
    },
  },
  {
    id: 'ocean',
    name: 'Ocean',
    emoji: '◍',
    dark: true,
    previewColors: ['#021020', '#05294a', '#38bdf8', '#bae6fd'],
    background: { label: 'Midnight', bg: '#0f172a', dot: '#1e293b' },
    vars: {
      widgetBg:           '#021020',
      widgetBorder:       '#05294a',
      widgetBorderActive: '#0c4a6e',
      shadowSm:           '0 1px 4px rgba(0,150,220,0.12)',
      shadowMd:           '0 4px 16px rgba(0,150,220,0.18)',
      shadowLg:           '0 20px 48px rgba(0,150,220,0.25), 0 0 0 1px rgba(56,189,248,0.06)',
      backdropFilter:     'none',
      textPrimary:        '#bae6fd',
      textMuted:          '#1d6b96',
      surfaceSubtle:      '#031828',
      surfaceHover:       '#04223a',
      surfaceDanger:      '#1f0a0a',
      accent:             '#38bdf8',
      accentText:         '#001220',
      danger:             '#f87171',
      actionBg:           '#031828',
      actionBorder:       '#05294a',
      settingsBg:         '#031828',
      settingsBorder:     '#05294a',
      settingsDivider:    '#041c32',
      settingsLabel:      '#1d6b96',
      scrollThumb:        '#0c4a6e',
      clockFaceFill:      '#021020',
      clockFaceStroke:    '#05294a',
      clockTickMajor:     '#0c4a6e',
      clockTickMinor:     '#042038',
      clockHands:         '#7dd3fc',
      clockSecond:        '#38bdf8',
      clockCenter:        '#7dd3fc',
      noteDefaultBg:      '#031828',
    },
  },
  {
    id: 'terminal',
    name: 'Terminal',
    emoji: '▶',
    dark: true,
    previewColors: ['#0a0a0a', '#1a1a1a', '#00ff41', '#00cc33'],
    background: { label: 'Void', bg: '#0a0a0a', dot: '#1a1a1a' },
    vars: {
      widgetBg:           '#0a0a0a',
      widgetBorder:       '#1a1a1a',
      widgetBorderActive: '#00ff41',
      shadowSm:           '0 1px 4px rgba(0,255,65,0.1)',
      shadowMd:           '0 4px 16px rgba(0,255,65,0.12)',
      shadowLg:           '0 20px 48px rgba(0,255,65,0.18)',
      backdropFilter:     'none',
      textPrimary:        '#00ff41',
      textMuted:          '#006618',
      surfaceSubtle:      '#0d0d0d',
      surfaceHover:       '#141414',
      surfaceDanger:      '#1a0000',
      accent:             '#00ff41',
      accentText:         '#000000',
      danger:             '#ff0000',
      actionBg:           '#0d0d0d',
      actionBorder:       '#1a1a1a',
      settingsBg:         '#0d0d0d',
      settingsBorder:     '#1a1a1a',
      settingsDivider:    '#111111',
      settingsLabel:      '#006618',
      scrollThumb:        '#00a828',
      clockFaceFill:      '#0a0a0a',
      clockFaceStroke:    '#00a828',
      clockTickMajor:     '#00a828',
      clockTickMinor:     '#004010',
      clockHands:         '#00ff41',
      clockSecond:        '#00cc33',
      clockCenter:        '#00ff41',
      noteDefaultBg:      '#001408',
    },
  },
  {
    id: 'carbon',
    name: 'Carbon',
    emoji: '◼',
    dark: true,
    previewColors: ['#161b22', '#30363d', '#58a6ff', '#e6edf3'],
    background: { label: 'Ink', bg: '#0d1117', dot: '#21262d' },
    vars: {
      widgetBg:           '#161b22',
      widgetBorder:       '#30363d',
      widgetBorderActive: '#484f58',
      shadowSm:           '0 1px 3px rgba(0,0,0,0.5)',
      shadowMd:           '0 4px 16px rgba(0,0,0,0.6)',
      shadowLg:           '0 20px 48px rgba(0,0,0,0.8)',
      backdropFilter:     'none',
      textPrimary:        '#e6edf3',
      textMuted:          '#484f58',
      surfaceSubtle:      '#0d1117',
      surfaceHover:       '#21262d',
      surfaceDanger:      '#2a1515',
      accent:             '#58a6ff',
      accentText:         '#0d1117',
      danger:             '#f85149',
      actionBg:           '#161b22',
      actionBorder:       '#30363d',
      settingsBg:         '#161b22',
      settingsBorder:     '#30363d',
      settingsDivider:    '#21262d',
      settingsLabel:      '#484f58',
      scrollThumb:        '#30363d',
      clockFaceFill:      '#161b22',
      clockFaceStroke:    '#30363d',
      clockTickMajor:     '#484f58',
      clockTickMinor:     '#30363d',
      clockHands:         '#c9d1d9',
      clockSecond:        '#58a6ff',
      clockCenter:        '#c9d1d9',
      noteDefaultBg:      '#21262d',
    },
  },
  {
    id: 'dusk',
    name: 'Dusk',
    emoji: '◉',
    dark: true,
    previewColors: ['#12101e', '#2d2850', '#a78bfa', '#ede9fe'],
    background: { label: 'Twilight', bg: '#0e0c1a', dot: '#1e1a35' },
    vars: {
      widgetBg:           '#12101e',
      widgetBorder:       '#2d2850',
      widgetBorderActive: '#4c3d8a',
      shadowSm:           '0 1px 3px rgba(0,0,0,0.5)',
      shadowMd:           '0 4px 16px rgba(80,40,180,0.2)',
      shadowLg:           '0 20px 48px rgba(80,40,180,0.3)',
      backdropFilter:     'none',
      textPrimary:        '#ede9fe',
      textMuted:          '#4c3d8a',
      surfaceSubtle:      '#0e0c1a',
      surfaceHover:       '#1e1a35',
      surfaceDanger:      '#2a1520',
      accent:             '#a78bfa',
      accentText:         '#0e0c1a',
      danger:             '#f87171',
      actionBg:           '#12101e',
      actionBorder:       '#2d2850',
      settingsBg:         '#12101e',
      settingsBorder:     '#2d2850',
      settingsDivider:    '#1e1a35',
      settingsLabel:      '#4c3d8a',
      scrollThumb:        '#4c3d8a',
      clockFaceFill:      '#12101e',
      clockFaceStroke:    '#2d2850',
      clockTickMajor:     '#4c3d8a',
      clockTickMinor:     '#2d2850',
      clockHands:         '#c4b5fd',
      clockSecond:        '#a78bfa',
      clockCenter:        '#c4b5fd',
      noteDefaultBg:      '#1e1a35',
    },
  },
  {
    id: 'espresso',
    name: 'Espresso',
    emoji: '▪',
    dark: true,
    previewColors: ['#1c1410', '#3d2b1e', '#d97706', '#f5e6d0'],
    background: { label: 'Roast', bg: '#140f0a', dot: '#2a1e12' },
    vars: {
      widgetBg:           '#1c1410',
      widgetBorder:       '#3d2b1e',
      widgetBorderActive: '#6b4226',
      shadowSm:           '0 1px 3px rgba(0,0,0,0.5)',
      shadowMd:           '0 4px 16px rgba(80,40,0,0.3)',
      shadowLg:           '0 20px 48px rgba(80,40,0,0.4)',
      backdropFilter:     'none',
      textPrimary:        '#f5e6d0',
      textMuted:          '#6b4226',
      surfaceSubtle:      '#140f0a',
      surfaceHover:       '#2a1e12',
      surfaceDanger:      '#2a1010',
      accent:             '#d97706',
      accentText:         '#140f0a',
      danger:             '#f87171',
      actionBg:           '#1c1410',
      actionBorder:       '#3d2b1e',
      settingsBg:         '#1c1410',
      settingsBorder:     '#3d2b1e',
      settingsDivider:    '#2a1e12',
      settingsLabel:      '#6b4226',
      scrollThumb:        '#6b4226',
      clockFaceFill:      '#1c1410',
      clockFaceStroke:    '#3d2b1e',
      clockTickMajor:     '#6b4226',
      clockTickMinor:     '#3d2b1e',
      clockHands:         '#e5c9a0',
      clockSecond:        '#d97706',
      clockCenter:        '#e5c9a0',
      noteDefaultBg:      '#2a1e12',
    },
  },
  {
    id: 'slate-dark',
    name: 'Slate Dark',
    emoji: '▣',
    dark: true,
    previewColors: ['#0f172a', '#1e293b', '#38bdf8', '#e2e8f0'],
    background: { label: 'Slate Night', bg: '#080f1e', dot: '#162032' },
    vars: {
      widgetBg:           '#0f172a',
      widgetBorder:       '#1e293b',
      widgetBorderActive: '#334155',
      shadowSm:           '0 1px 3px rgba(0,0,0,0.5)',
      shadowMd:           '0 4px 16px rgba(0,0,0,0.6)',
      shadowLg:           '0 20px 48px rgba(0,0,0,0.8)',
      backdropFilter:     'none',
      textPrimary:        '#e2e8f0',
      textMuted:          '#475569',
      surfaceSubtle:      '#080f1e',
      surfaceHover:       '#162032',
      surfaceDanger:      '#2a1515',
      accent:             '#38bdf8',
      accentText:         '#0f172a',
      danger:             '#f87171',
      actionBg:           '#0f172a',
      actionBorder:       '#1e293b',
      settingsBg:         '#0f172a',
      settingsBorder:     '#1e293b',
      settingsDivider:    '#162032',
      settingsLabel:      '#475569',
      scrollThumb:        '#334155',
      clockFaceFill:      '#0f172a',
      clockFaceStroke:    '#1e293b',
      clockTickMajor:     '#475569',
      clockTickMinor:     '#1e293b',
      clockHands:         '#cbd5e1',
      clockSecond:        '#38bdf8',
      clockCenter:        '#cbd5e1',
      noteDefaultBg:      '#162032',
    },
  },
]

export const THEME_MAP = Object.fromEntries(THEMES.map((t) => [t.id, t]))

export const CSS_VAR_MAP: Record<keyof ThemeVars, string> = {
  widgetBg:           '--wt-bg',
  widgetBorder:       '--wt-border',
  widgetBorderActive: '--wt-border-active',
  shadowSm:           '--wt-shadow-sm',
  shadowMd:           '--wt-shadow-md',
  shadowLg:           '--wt-shadow-lg',
  backdropFilter:     '--wt-backdrop',
  textPrimary:        '--wt-text',
  textMuted:          '--wt-text-muted',
  surfaceSubtle:      '--wt-surface',
  surfaceHover:       '--wt-surface-hover',
  surfaceDanger:      '--wt-surface-danger',
  accent:             '--wt-accent',
  accentText:         '--wt-accent-text',
  danger:             '--wt-danger',
  actionBg:           '--wt-action-bg',
  actionBorder:       '--wt-action-border',
  settingsBg:         '--wt-settings-bg',
  settingsBorder:     '--wt-settings-border',
  settingsDivider:    '--wt-settings-divider',
  settingsLabel:      '--wt-settings-label',
  scrollThumb:        '--wt-scroll-thumb',
  clockFaceFill:      '--wt-clock-face',
  clockFaceStroke:    '--wt-clock-stroke',
  clockTickMajor:     '--wt-clock-tick-major',
  clockTickMinor:     '--wt-clock-tick-minor',
  clockHands:         '--wt-clock-hands',
  clockSecond:        '--wt-clock-second',
  clockCenter:        '--wt-clock-center',
  noteDefaultBg:      '--wt-note-bg',
}

export function applyThemeVars(vars: ThemeVars) {
  const root = document.documentElement
  for (const [key, cssVar] of Object.entries(CSS_VAR_MAP)) {
    root.style.setProperty(cssVar, vars[key as keyof ThemeVars])
  }
}
